### ISSUE TITLE
array_flip(): Can only flip STRING and INTEGER values! GeoJson.php:84                                                                      [warning]

### ISSUE THREAD

**Issue by plopesc** [savaslabs/views_geojson#50]
Hello @timstallmann 

I'm trying your last changes from yesterday and I'm having this error
array_flip(): Can only flip STRING and INTEGER values! GeoJson.php:84                                                                      [warning]

Could you take a look here, please?

Thanks

**Comment by plopesc** [comment]
@timstallmann 
$this->getExcludedFields can't be called from the class constructor because the data is not yet available.

$this->excludedFields = [null, null]

I think best option is to calculate it once in line 324 or call pass it as a parameter to renderRow() as it wa at the beginning.

Thanks

**Comment by plopesc** [comment]
Also getting this error 

> Notice: Undefined index: data_source in Drupal\views_geojson\Plugin\views\style\GeoJson->getExcludedFields() line 492 of /var/www/drupalvm/web/modules/contrib/views_geojson/src/Plugin/vie

Because datasource is not available at class construct time.

**Comment by plopesc** [comment]
I think best option is to revert your last commits and leave that part of the code as it was in my original Pull Request

**Comment by timstallmann** [comment]
@plopesc that makes sense to me -- do you want to submit the PR or should I? Only in that case we should probably remove the `$excludedFields` property from the object since it is not used anywhere

**Comment by plopesc** [comment]
@timstallmann you can do it if you want, I can make it tonight if you don't have room today.

Yes let's remove $excludedFields, I forgot to remove it from my previous tests.

Thanks!
